# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
# ZSH_THEME="random"
# ZSH_THEME="cloud"
ZSH_THEME="ys"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

# User configuration

export GOPATH="$HOME/working/GOPATH"
export PATH="$PATH:$GOPATH/bin:$HOME/.rvm/gems/ruby-head/bin:$HOME/.rvm/gems/ruby-head@global/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$HOME/.rvm/bin:/usr/local/opt/go/libexec/bin"

export PATH=$PATH:~/bin
# export EDITOR="subl -w"

# export MANPATH="/usr/local/man:$MANPATH"

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
 export LANG=en_US.UTF-8
 export LC_ALL=en_US.UTF-8

# init byobu
# export BYOBU_PREFIX=$(brew --prefix)

# Preferred editor for local and remote sessions

if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  # add -f  or  --nofork     Foreground: Don't fork when starting GUI
  # to prevent git from automatically assuming no input during commit editing
  export EDITOR='mvim --nofork'
fi

export VISUAL=$EDITOR

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion


# workaround for subl not working in tmux
# alias subl='reattach-to-user-namespace subl'

# set up Vagrant home directory
# export VAGRANT_HOME='/Volumes/ZEDDEE/vagrant-working/'

# The next line updates PATH for the Google Cloud SDK.
# if [ -f /Volumes/ZEDDEE/working/google-cloud-sdk/path.zsh.inc ]; then
#   source '/Volumes/ZEDDEE/working/google-cloud-sdk/path.zsh.inc'
# fi

# The next line enables shell command completion for gcloud.
# if [ -f /Volumes/ZEDDEE/working/google-cloud-sdk/completion.zsh.inc ]; then
#   source '/Volumes/ZEDDEE/working/google-cloud-sdk/completion.zsh.inc'
# fi

export HOMEBREW_INSTALL_BADGE=🍺
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home
JRE_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre

HOMEBREW_GITHUB_API_TOKEN=66a927f29d7540fd217271efc24821c6956e095a



# Path for LaTeX
# export PATH="$PATH:/Library/TeX/Distributions/Programs/texbin"

# Path for Cargo (Rustup)
# export PATH="$HOME/.cargo/bin:$PATH"

export RESTIC_REPOSITORY=/Volumes/ShipOTheseus

# Add bash aliases.
if [ -f $HOME/.aliases ]; then
    source $HOME/.aliases
    echo Loaded aliases
fi

# Export local python bin
export PATH="$PATH:$HOME/Library/Python/3.6/bin"


# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
# RVM fix for zsh
[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm" 

alias adoc=asciidoctor
alias adocpdf=asciidoctor-pdf

ssh-add $HOME/.ssh/id_eiq_github

