if [[ $(command -v cargo) ]]; then
. "$HOME/.cargo/env"
fi

export PATH=$PATH:$HOME/.local/bin:$HOME/.pyenv/bin:/var/lib/snapd/snap/bin

if [[ $(command -v nvim) ]]; then
export EDITOR="nvim"
fi

if [[ -f ~/working/.pritunl ]]; then
source ~/working/.pritunl
fi

if [[ $(command -v direnv) ]]; then
eval "$(direnv hook zsh)"
fi

if [[ $(command -v pyenv) ]]; then
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
fi
