. "$HOME/.cargo/env"
export PATH=$PATH:$HOME/.local/bin:$HOME/.pyenv/bin:/var/lib/snapd/snap/bin
export EDITOR="nvim"

source ~/working/.pritunl

eval "$(direnv hook zsh)"

export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
